

runtime: python37

env_variables:
  CLOUD_SQL_USERNAME:system
  CLOUD_SQL_PASSWORD:12345678
  CLOUD_SQL_DATABASE_NAME: cloudsqltest
  CLOUD_SQL_CONNECTION_NAME: sqlproject-331715:us-central1:testmysql